// Re-export all vehicle-related functions and types for convenience
export {
  fetchVehicles,
  fetchVehicleById,
  createVehicle,
  updateVehicle,
  deleteVehicle,
  toggleVehicleStatus,
  getVehicleName,
  type Vehicle,
  type VehiclesApiResponse,
  type VehicleFilters,
  type CreateVehiclePayload,
  type UpdateVehiclePayload,
  type VehicleName,
  type VehicleDescription,
  type VehicleFeature,
  type VehicleOffer,
  type VehicleAccessory,
  type VehiclePackage,
  type VehicleImage,
  type VehicleBrand,
  type VehicleAgent,
  type VehicleModel,
} from "./fetchVehicles";
